/** レーティング対象として表示する規定枠数。 */
export const RATING_SLOT_COUNT = {
  best: 30,
  new: 20,
} as const

/** 新曲枠レーティング理論値サマリーで使用する文言。 */
export const NEW_SONG_RATING_SUMMARY_COPY = {
  ariaLabel: '新曲枠レーティング理論値',
  theoreticalRating: '理論値',
  currentGap: '現在との差',
  loadingLabel: '新曲枠レーティング理論値を計算中',
  noData: '新曲枠対象譜面がありません',
  emptyValue: '-',
  unknownChartConstant: '未確定の譜面定数を含む推定値',
  unknownMarker: '?',
  detailsLabel: '最高到達対象譜面',
  chartCountSuffix: '譜面',
  singleRatingLabel: '単曲RATING',
  chartConstantLabel: '譜面定数',
  currentSlotLabel: '新曲枠',
  candidateSlotLabel: '候補',
  currentScoreLabel: '現在スコア',
  scoreGapLabel: '理論まで',
  recordUnavailable: '現在枠外',
} as const

/** レーティング枠画像の固定論理幅。 */
export const RATING_IMAGE_WIDTH_PX = 1_024
/** レーティング枠画像を原寸の2倍で出力するピクセル比。 */
export const RATING_IMAGE_PIXEL_RATIO = 2

/** レーティング枠画像化プレビューで使用する文言。 */
export const RATING_IMAGE_COPY = {
  openPreview: '画像化',
  dialogTitle: '画像化プレビュー',
  dialogDescription: '現在のテーマとジャケット表示設定で画像を作成します。',
  preparingPreview: '画像化プレビューを準備中',
  bestHeading: 'ベスト枠',
  newHeading: '新曲枠',
  averageLabel: 'Avg.',
  ratingLabel: 'RATING',
  overPowerLabel: 'OP',
  overPowerPercentLabel: 'OP%',
  generatedBy: 'Generated by ChuniSupport',
  close: '閉じる',
  download: '画像をダウンロード',
  downloading: '画像を作成中',
  downloadError: '画像のダウンロードに失敗しました。',
} as const

/**
 * 空きレーティング枠の読み上げ文言を生成する。
 *
 * @param slotNumber - 1始まりの枠番号。
 * @returns 空き枠であることを示す読み上げ文言。
 */
export const buildEmptyRatingSlotLabel = (slotNumber: number): string => `${slotNumber}番は空き枠`
