/** レーティング枠画像の固定論理幅 */
export const RATING_IMAGE_WIDTH_PX = 1_024
/** レーティング枠画像 Ver. 2 の固定論理幅 */
export const RATING_IMAGE_V2_WIDTH_PX = 1_040
/** レーティング枠画像 Ver. 2 の外周余白 */
export const RATING_IMAGE_V2_PADDING_PX = 20
/** レーティング枠画像 Ver. 2 のジャケット間隔 */
export const RATING_IMAGE_V2_GAP_PX = 10
/** レーティング枠画像 Ver. 2 のジャケット列数 */
export const RATING_IMAGE_V2_COLUMN_COUNT = 5
/** レーティング枠画像 Ver. 2 のジャケット一辺 */
export const RATING_IMAGE_V2_JACKET_PX = 100
/** レーティング枠画像 Ver. 2 の難易度コーナーラベル一辺 */
export const RATING_IMAGE_V2_DIFFICULTY_CORNER_PX = 32
/** レーティング枠画像 Ver. 2 の称号列幅 */
export const RATING_IMAGE_V2_HONOR_COLUMN_PX = 280
/** レーティング枠画像 Ver. 2 の譜面カード内余白 */
export const RATING_IMAGE_V2_CARD_PADDING_PX = 8
/** レーティング枠画像 Ver. 2 のジャケット左の数値列幅 */
export const RATING_IMAGE_V2_META_WIDTH_PX = 64
/** レーティング枠画像 Ver. 2 の数値列とジャケットの間隔 */
export const RATING_IMAGE_V2_META_GAP_PX = 6
/** レーティング枠画像を原寸で出力するピクセル比 */
export const RATING_IMAGE_PIXEL_RATIO = 1
/** レーティング枠JPEG画像の圧縮品質 */
export const RATING_IMAGE_JPEG_QUALITY = 0.9

/** レーティング枠画像のデザインバージョン */
export type RatingImageVersion = 'v1' | 'v2'

/** レーティング枠画像のデザインバージョン選択肢 */
export type RatingImageVersionOption = {
  /** 画像化に使うデザインバージョン */
  value: RatingImageVersion
  /** プルダウンへ表示するラベル */
  label: string
}

/** レーティング枠画像のデザインバージョン一覧 */
export const RATING_IMAGE_VERSION_OPTIONS: RatingImageVersionOption[] = [
  { value: 'v1', label: 'Ver. 1' },
  { value: 'v2', label: 'Ver. 2' },
]

/** レーティング枠画像化プレビューで使用する文言 */
export const RATING_IMAGE_COPY = {
  openPreview: '画像化',
  dialogTitle: 'プレビュー',
  dialogDescription: '現在のテーマとジャケット表示設定で画像を作成します。',
  versionLabel: 'デザインバージョン',
  preparingPreview: 'プレビューを準備中',
  previewAlt: 'ベスト枠と新曲枠の画像プレビュー',
  previewError: 'プレビューの作成に失敗しました。',
  retryPreview: '再試行',
  bestHeading: 'ベスト枠',
  newHeading: '新曲枠',
  averageLabel: 'Avg.',
  ratingLabel: 'RATING',
  bestAverageLabel: 'BEST',
  newAverageLabel: 'NEW',
  overPowerLabel: 'OP',
  overPowerPercentLabel: 'OP%',
  emptyHonorSlot: '空き称号枠',
  generatedBy: 'Generated by ChuniSupport',
  close: '閉じる',
  share: '共有',
  shareError: '共有に失敗しました。',
} as const

/**
 * 空きレーティング枠の読み上げ文言を生成する。
 *
 * @param slotNumber - 1始まりの枠番号。
 * @returns 空き枠であることを示す読み上げ文言。
 */
export const buildEmptyRatingSlotLabel = (slotNumber: number): string => `${slotNumber}番は空き枠`
