/** レーティング枠画像の固定論理幅 */
export const RATING_IMAGE_WIDTH_PX = 1_024
/** レーティング枠画像 Ver. 2 の固定論理幅 */
export const RATING_IMAGE_V2_WIDTH_PX = 1_040
/** レーティング枠画像 Ver. 2 の外周余白 */
export const RATING_IMAGE_V2_PADDING_PX = 20
/** レーティング枠画像 Ver. 2 のジャケット間隔 */
export const RATING_IMAGE_V2_GAP_PX = 10
/** レーティング枠画像 Ver. 2 のジャケット列数 */
export const RATING_IMAGE_V2_COLUMN_COUNT = 5
/** レーティング枠画像 Ver. 2 のジャケット一辺 */
export const RATING_IMAGE_V2_JACKET_PX = 100
/** レーティング枠画像 Ver. 2 の称号列幅 */
export const RATING_IMAGE_V2_HONOR_COLUMN_PX = 340
/** レーティング枠画像 Ver. 2 の譜面カード内余白 */
export const RATING_IMAGE_V2_CARD_PADDING_PX = 8
/** レーティング枠画像 Ver. 2 の左端難易度縦線の幅 */
export const RATING_IMAGE_V2_DIFFICULTY_STRIPE_PX = 4
/** レーティング枠画像 Ver. 2 のジャケット左の数値列幅 */
export const RATING_IMAGE_V2_META_WIDTH_PX = 64
/** レーティング枠画像 Ver. 2 の数値列とジャケットの間隔 */
export const RATING_IMAGE_V2_META_GAP_PX = 6
/** レーティング枠画像 Ver. 2 の譜面定数とレーティングの間の下向き三角形一辺 */
export const RATING_IMAGE_V2_META_TRIANGLE_PX = 12
/** レーティング枠画像 Ver. 2 の譜面定数・三角形・レーティングの間隔 */
export const RATING_IMAGE_V2_META_TRIANGLE_GAP_PX = 8
/**
 * レーティング枠画像 Ver. 2 のジャケット左上コンボランプエンブレムの SVG 表示領域一辺。
 * ジャケット左上へ配置し、この領域の中心をエンブレムの中心とする。
 */
export const RATING_IMAGE_V2_JACKET_LAMP_CANVAS_PX = 28
/** コンボランプエンブレムの菱形（回転前の角丸正方形）一辺 */
export const RATING_IMAGE_V2_JACKET_LAMP_DIAMOND_PX = 18
/** コンボランプエンブレムの菱形の白フチ幅 */
export const RATING_IMAGE_V2_JACKET_LAMP_FRAME_PX = 2
/** コンボランプエンブレムの菱形の角丸半径 */
export const RATING_IMAGE_V2_JACKET_LAMP_RADIUS_PX = 4
/** コンボランプエンブレムの菱形と文字をまとめて囲む外周濃色線の幅 */
export const RATING_IMAGE_V2_JACKET_LAMP_OUTLINE_PX = 0.9
/** コンボランプエンブレムの文字を囲む白フチ幅 */
export const RATING_IMAGE_V2_JACKET_LAMP_TEXT_FRAME_PX = 1.6
/**
 * コンボランプエンブレムの略称をアウトライン化した SVG パス（エンブレム中心が原点）。
 * 端末のフォント読み込み状況に左右されないよう、Oswald Bold の字形を
 * 文字サイズ 16px・文字間隔 -0.02em・ベースライン下方向 7.232px（文字サイズ比 0.452）で
 * 中央揃えに配置した座標を埋め込んでいる。
 */
export const RATING_IMAGE_V2_JACKET_LAMP_LABEL_PATHS = {
  'FULL COMBO':
    'M-6.86 7.23V-5.73H-1.26V-3.79H-3.99V-0.53H-1.61V1.47H-3.99V7.23ZM3.48 7.42Q2.01 7.42 1.15 6.89Q0.3 6.35 -0.06 5.38Q-0.41 4.42 -0.41 3.1V-1.57Q-0.41 -2.91 -0.06 -3.88Q0.3 -4.85 1.15 -5.38Q2.01 -5.9 3.48 -5.9Q4.92 -5.9 5.73 -5.43Q6.54 -4.96 6.87 -4.11Q7.21 -3.26 7.21 -2.16V-1.04H4.41V-2.34Q4.41 -2.72 4.37 -3.07Q4.33 -3.42 4.14 -3.66Q3.94 -3.89 3.48 -3.89Q3.03 -3.89 2.82 -3.65Q2.6 -3.41 2.54 -3.05Q2.49 -2.69 2.49 -2.29V3.81Q2.49 4.24 2.56 4.6Q2.63 4.96 2.85 5.18Q3.06 5.39 3.48 5.39Q3.93 5.39 4.12 5.16Q4.31 4.93 4.36 4.56Q4.41 4.19 4.41 3.81V2.45H7.21V3.57Q7.21 4.67 6.88 5.54Q6.55 6.42 5.74 6.92Q4.94 7.42 3.48 7.42Z',
  'ALL JUSTICE':
    'M-6.7 7.23 -4.26 -5.73H-0.99L1.42 7.23H-1.22L-1.65 4.5H-3.55L-4 7.23ZM-3.3 2.78H-1.92L-2.61 -2.27ZM1.66 7.57V5.57Q2.1 5.57 2.4 5.52Q2.7 5.47 2.88 5.34Q3.06 5.2 3.14 4.94Q3.22 4.67 3.22 4.26V-5.73H6.08V4.38Q6.08 5.44 5.82 6.15Q5.55 6.86 4.9 7.22Q4.24 7.57 3.06 7.57Z',
} as const

/**
 * レーティング枠画像 Ver. 2 の最新更新 NEW! バッジ。
 * 画像化対象とプレビュー設定チェックボックスで同じ見た目を共有する。
 */
export const RATING_IMAGE_V2_NEW_BADGE_CLASS =
  'rating-image-v2-new-badge whitespace-nowrap font-jost text-[18px] font-black leading-none text-white italic'
/** レーティング枠画像を原寸で出力するピクセル比 */
export const RATING_IMAGE_PIXEL_RATIO = 1
/** レーティング枠JPEG画像の圧縮品質 */
export const RATING_IMAGE_JPEG_QUALITY = 0.9

/** レーティング枠画像のデザインバージョン */
export type RatingImageVersion = 'v1' | 'v2'

/** レーティング枠画像のデザインバージョン選択肢 */
export type RatingImageVersionOption = {
  /** 画像化に使うデザインバージョン */
  value: RatingImageVersion
  /** プルダウンへ表示するラベル */
  label: string
}

/** レーティング枠画像化で初期選択するデザインバージョン */
export const RATING_IMAGE_DEFAULT_VERSION_OPTION: RatingImageVersionOption = {
  value: 'v2',
  label: 'Ver. 2',
}

/** レーティング枠画像のデザインバージョン一覧 */
export const RATING_IMAGE_VERSION_OPTIONS: RatingImageVersionOption[] = [
  { value: 'v1', label: 'Ver. 1' },
  RATING_IMAGE_DEFAULT_VERSION_OPTION,
]

/** レーティング枠画像化プレビューで使用する文言 */
export const RATING_IMAGE_COPY = {
  openPreview: '画像化',
  dialogTitle: 'プレビュー',
  dialogDescription: '長押しまたは右クリックで画像を保存できます。',
  versionLabel: 'デザインバージョン',
  v2OptionsLegend: '表示設定',
  showLatestUpdateBadgeLabel: 'ラベルを表示',
  applyPossessionLabel: 'ポゼッションを反映',
  hidePlayerLevelLabel: 'プレイヤーレベルを非表示',
  hideClassEmblemLabel: 'エンブレムを非表示',
  preparingPreview: 'プレビューを準備中',
  previewAlt: 'ベスト枠と新曲枠の画像プレビュー',
  previewError: 'プレビューの作成に失敗しました。',
  retryPreview: '再試行',
  bestHeading: 'ベスト枠',
  newHeading: '新曲枠',
  bestV2Heading: 'BEST',
  newV2Heading: 'NEW',
  latestUpdateBadge: 'NEW!',
  averageLabel: 'Avg.',
  ratingLabel: 'RATING',
  bestAverageLabel: 'BEST',
  newAverageLabel: 'NEW',
  overPowerLabel: 'OP',
  overPowerFullLabel: 'OVER POWER',
  overPowerPercentLabel: 'OP%',
  emptyHonorSlot: '空き称号枠',
  generatedByPrefix: 'Generated by ',
  generatedByUrl: 'https://chunisupport.net/',
  jacketCopyright: '楽曲ジャケット画像の著作権は、すべて著作権保持者に帰属します。',
  unofficialDisclaimer:
    'この画像は非公式ツールによるものであり、株式会社セガ及びその関連会社とは一切関係ありません。',
  close: '閉じる',
  share: '共有',
  shareError: '共有に失敗しました。',
} as const

/**
 * 空きレーティング枠の読み上げ文言を生成する。
 *
 * @param slotNumber - 1始まりの枠番号。
 * @returns 空き枠であることを示す読み上げ文言。
 */
export const buildEmptyRatingSlotLabel = (slotNumber: number): string => `${slotNumber}番は空き枠`
