import {
  OVER_POWER_MASTER_ULTIMA_TARGET,
  OVER_POWER_THEORETICAL_TARGET,
} from '../../../usecases/overpower/constants'
import type { OverPowerRecordFilterDimension } from '../../../usecases/overpower/recordNavigation'
import type { OverPowerSubPage } from '../../../utils/userProfileRoute'
import type {
  OverPowerAggregationTargetOption,
  OverPowerComboBand,
  OverPowerScoreBand,
  OverPowerSummaryOption,
  OverPowerSummaryTab,
  OverPowerSummaryViewMode,
} from './types'

/** OVERPOWERサマリーを開いたときに最初に表示する表示形式 */
export const DEFAULT_OVER_POWER_SUMMARY_VIEW_MODE: OverPowerSummaryViewMode = 'graph'

/** レベル別集計で初期状態では折りたたむ低レベル帯の表示名 */
export const LOW_LEVEL_SUMMARY_LABEL = 'Lv.1-9+'

/** OVER POWERサマリーの表示軸選択肢 */
export const OVER_POWER_SUMMARY_OPTIONS: OverPowerSummaryOption[] = [
  { value: 'genres', label: 'ジャンル' },
  { value: 'levels', label: 'レベル' },
  { value: 'versions', label: 'バージョン' },
]

/** OVER POWERサマリーの集計対象選択肢 */
export const OVER_POWER_AGGREGATION_TARGET_OPTIONS: OverPowerAggregationTargetOption[] = [
  { value: 'OP_TARGET', label: 'OVER POWER対象' },
  { value: OVER_POWER_THEORETICAL_TARGET, label: 'OP理論値対象' },
  { value: 'BASIC', label: 'BASIC' },
  { value: 'ADVANCED', label: 'ADVANCED' },
  { value: 'EXPERT', label: 'EXPERT' },
  { value: 'MASTER', label: 'MASTER' },
  { value: 'ULTIMA', label: 'ULTIMA' },
  { value: OVER_POWER_MASTER_ULTIMA_TARGET, label: 'MASTER + ULTIMA' },
  { value: 'ALL', label: '全難易度' },
]

/** OVER POWER集計画面で表示する達成率の小数点以下桁数 */
export const OVER_POWER_SUMMARY_PERCENT_DECIMAL_PLACES = 5

/** 未解禁曲を集計対象から除外するチェックボックスのラベル */
export const OVER_POWER_LOCKED_SONG_EXCLUSION_LABEL = '未解禁曲を計算から除外する'

/** 未解禁楽曲設定ダイアログで要解禁楽曲だけを表示する初期状態 */
export const DEFAULT_LOCKED_SONGS_UNLOCK_REQUIRED_ONLY = true

/** 未解禁楽曲設定ダイアログの要解禁楽曲表示操作のラベル */
export const LOCKED_SONGS_UNLOCK_REQUIRED_ONLY_LABEL = '要解禁楽曲のみ表示'

/** 未解禁楽曲設定ダイアログのプレイ状況フィルター */
export type LockedSongsPlayStatus = 'played' | 'unplayed'

/** 未解禁楽曲設定ダイアログのプレイ状況フィルター選択肢 */
export const LOCKED_SONG_PLAY_STATUS_OPTIONS = [
  { value: 'unplayed', label: '未プレイ' },
  { value: 'played', label: 'プレイ済み' },
] as const

/** 未解禁楽曲設定ダイアログのプレイ状況フィルター表示文言 */
export const LOCKED_SONG_PLAY_STATUS_FILTER_COPY = {
  label: 'プレイ状況',
  suffix: 'のみ表示',
  ariaLabel: 'プレイ状況フィルターを有効にする',
} as const

/** 通常レコードへのフィルター付き遷移に失敗したときの表示文言 */
export const OVER_POWER_RECORD_NAVIGATION_ERROR_MESSAGE = 'レコードの表示に失敗しました。'

/** 未解禁楽曲設定ダイアログで公式値と計算値を見比べる表示の文言 */
export const LOCKED_SONGS_OP_COMPARISON_COPY = {
  disclosureLabel: '公式値との照合',
  official: '公式値',
  calculated: '計算値',
  kind: '種別',
  overPower: 'OP',
  overPowerPercent: 'OP%',
  matched: '一致',
  mismatched: '差異あり',
  missingValue: '-',
  guidance: {
    overPowerHigher: 'プレイ済みの未解禁楽曲があります',
    overPowerLower: 'プレイ済み・解禁済みの楽曲を未解禁に指定しています',
    overPowerPercentHigher: '解禁済み楽曲を未解禁設定しています',
    overPowerPercentLower: '未設定の未解禁曲があります',
  },
} as const

/** OVER POWER画面の操作ラベル */
export const OVER_POWER_CONTROL_LABELS = {
  aggregationTarget: '集計対象',
  lockedSongs: '未解禁曲',
  lockedSongsSettings: '未解禁楽曲設定',
  songCount: '曲数',
  chartCount: '譜面数',
  graph: 'グラフ',
  table: 'テーブル',
} as const

/** OVER POWER画像化の表示文言 */
export const OVER_POWER_IMAGE_COPY = {
  triggerLabel: '画像化',
  previewTitle: 'OVER POWER画像',
  previewAlt: 'OVER POWER画像のプレビュー',
  sheetTitle: 'OVER POWER',
  generatedBy: 'Generated by',
} as const

/** OVER POWER画像で横に並べるカード枚数 */
export const OVER_POWER_IMAGE_COLUMNS = 3

/** OVER POWER画像のカード幅の基準にする画面幅 */
const OVER_POWER_IMAGE_REFERENCE_VIEWPORT_WIDTH = 430

/** OVER POWER画面の左右余白（mx-4相当）の合計 */
const OVER_POWER_PAGE_HORIZONTAL_MARGIN = 32

/** OVER POWER画像のカード1枚の幅。画面幅430pxで表示したときのカード幅に揃える */
export const OVER_POWER_IMAGE_CARD_WIDTH =
  OVER_POWER_IMAGE_REFERENCE_VIEWPORT_WIDTH - OVER_POWER_PAGE_HORIZONTAL_MARGIN

/** OVER POWER画像のカード間の余白（gap-4相当） */
export const OVER_POWER_IMAGE_CARD_GAP = 16

/** OVER POWER画像の外周余白（p-6相当） */
export const OVER_POWER_IMAGE_PADDING = 24

/** OVER POWER画像の論理幅。カード列、カード間の余白、外周余白の合計 */
export const OVER_POWER_IMAGE_WIDTH =
  OVER_POWER_IMAGE_CARD_WIDTH * OVER_POWER_IMAGE_COLUMNS +
  OVER_POWER_IMAGE_CARD_GAP * (OVER_POWER_IMAGE_COLUMNS - 1) +
  OVER_POWER_IMAGE_PADDING * 2

/** OVER POWER画像の出力ピクセル比。カード内の小さな文字を読めるよう2倍で出力する */
export const OVER_POWER_IMAGE_PIXEL_RATIO = 2

/** URLサブページからOVER POWERサマリーの表示軸へ変換する対応表 */
export const overPowerSummaryTabBySubPage: Record<OverPowerSubPage, OverPowerSummaryTab> = {
  genre: 'genres',
  level: 'levels',
  version: 'versions',
}

/** OVER POWERサマリーの表示軸からURLサブページへ変換する対応表 */
export const overPowerSubPageBySummaryTab: Record<OverPowerSummaryTab, OverPowerSubPage> = {
  genres: 'genre',
  levels: 'level',
  versions: 'version',
}

/** OVER POWERの表示軸から通常レコードへ引き継ぐ分類軸への対応 */
export const overPowerRecordFilterDimensionBySummaryTab: Record<
  OverPowerSummaryTab,
  OverPowerRecordFilterDimension
> = {
  genres: 'genre',
  levels: 'level',
  versions: 'version',
}

/** OVER POWERグラフで表示するスコア帯の順序 */
export const OVER_POWER_SCORE_BANDS: OverPowerScoreBand[] = [
  'MAX',
  'SSS+',
  'SSS',
  'SS+',
  'SS',
  'S+',
  'S',
  'OTHER',
]

/** OVER POWERグラフで表示するコンボ帯の順序 */
export const OVER_POWER_COMBO_BANDS: OverPowerComboBand[] = ['ALL JUSTICE', 'FULL COMBO', 'OTHER']
