export { AdminPage, AdminSongsPage, AdminUsersPage } from './admin'
export { Login, Register } from './auth'
export { EditorPage, EditorSongsPage } from './editor'
export { default as ForbiddenPage } from './ForbiddenPage'
export { GoalsList } from './goals'
export { default as NotFoundPage } from './NotFoundPage'
export { RegisterScoreTempPage } from './register-score-temp'
export { SettingsApiTokenPage, SettingsPage, SettingsPrivacyPage } from './settings'
export { SongDetail, SongsList, WorldsendSongDetail } from './songs'
export { UserPage } from './users'
