/**
 * サードパーティ製ソフトウェアのライセンス情報を集約した
 * THIRD-PARTY-NOTICES.txt を生成するスクリプト。
 *
 * - generate-license-file のライブラリ API を使用
 * - プロジェクト固有のヘッダーを先頭に付与
 * - リポジトリルートと public/ の両方に出力（配布物にも含めるため）
 *
 * 実行: pnpm licenses:generate
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getLicenseFileText } from 'generate-license-file'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')

const INPUT_PACKAGE_JSON = join(projectRoot, 'package.json')
const HEADER_FILE = join(projectRoot, 'scripts', 'THIRD-PARTY-NOTICES-HEADER.txt')
const OUTPUT_ROOT = join(projectRoot, 'THIRD-PARTY-NOTICES.txt')
const OUTPUT_PUBLIC = join(projectRoot, 'public', 'THIRD-PARTY-NOTICES.txt')
const OUTPUT_FILES = [OUTPUT_ROOT, OUTPUT_PUBLIC]
const isCheckMode = process.argv.includes('--check')

/**
 * ライセンス通知ファイルに書き込む本文を生成する。
 * @returns {Promise<string>} ヘッダーとツール生成分を結合したライセンス通知本文。
 */
async function createLicenseNoticeText() {
  const toolGeneratedText = await getLicenseFileText(INPUT_PACKAGE_JSON)
  const header = readFileSync(HEADER_FILE, 'utf8')

  // ツール生成分 + ヘッダー + 改行を組み合わせて出力
  // （ヘッダーは「先頭」に置きたいので、手動で結合）
  return [
    header.trimEnd(),
    '',
    '===============================================================================',
    'The following section was auto-generated by generate-license-file.',
    '===============================================================================',
    '',
    toolGeneratedText.trimEnd(),
    '',
  ].join('\n')
}

/**
 * ライセンスファイルを指定パスに書き込む。
 * @param {string} outputPath - 出力先ファイルパス。
 * @param {string} licenseNoticeText - 書き込むライセンス通知本文。
 * @returns {void}
 */
function writeLicenseNotice(outputPath, licenseNoticeText) {
  writeFileSync(outputPath, licenseNoticeText, 'utf8')
  console.log(`Generated: ${outputPath}`)
}

/**
 * 生成済みライセンスファイルが Git 管理下で最新か検証する。
 * @returns {void}
 */
function verifyGeneratedFiles() {
  try {
    execFileSync('git', ['ls-files', '--error-unmatch', '--', ...OUTPUT_FILES], {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: 'ignore',
    })
  } catch {
    console.error('License notice files are not tracked by Git.')
    console.error(OUTPUT_FILES.join('\n'))
    process.exit(1)
  }

  try {
    execFileSync('git', ['diff', '--exit-code', '--', ...OUTPUT_FILES], {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: 'inherit',
    })
  } catch {
    console.error('License notice files are not up to date.')
    process.exit(1)
  }
}

/**
 * ライセンス通知ファイルを生成し、必要に応じて Git 差分を検証する。
 * @returns {Promise<void>}
 */
async function main() {
  const licenseNoticeText = await createLicenseNoticeText()

  for (const outputFile of OUTPUT_FILES) {
    writeLicenseNotice(outputFile, licenseNoticeText)
  }

  if (isCheckMode) {
    verifyGeneratedFiles()
  }

  console.log('Done. Both THIRD-PARTY-NOTICES.txt files have been updated.')
}

main().catch((err) => {
  console.error('Failed to generate license notices:', err)
  process.exit(1)
})
