import {
  MASTER_ULTIMA_FILTER,
  THEORETICAL_OVER_POWER_TARGET_FILTER,
} from '../../../constants/chart'
import { NAME_FOLDER_LABELS } from '../../../constants/nameFolder'
import {
  PLAYER_STATS_ACHIEVEMENT_LABEL,
  type PlayerStatsHeatmapAxis,
} from '../../../constants/playerStats'
import type { PlayerStatsAchievement } from '../../../utils/playerStatsDashboard'
import type {
  UniFillMatrixDifficulty,
  UniFillMatrixDimension,
  UniFillMatrixHeader,
  UniFillMatrixViewSettings,
} from '../../../utils/uniFillMatrix'

/** ウニ埋めマトリックス画面の表示文言。タイトルと説明文はツール一覧の定義を参照すること。 */
export const UNI_FILL_MATRIX_COPY = {
  difficultyLabel: '難易度',
  achievementLabel: '埋め条件',
  axisLabel: '縦軸',
  horizontalAxisLabel: '横軸',
  swapAxesLabel: '縦軸と横軸を入れ替え',
  percentToggle: '%表示',
  totalHeader: '合計',
  cellActionLabel: '未達成の譜面をレコードで表示',
  recordNavigationError: 'レコード画面へ移動できませんでした。',
  imageSaveLabel: '画像化・共有',
  imageSaveError: '画像を生成できませんでした。',
  imageShareError: '画像を共有できませんでした。',
  imageCapturingLabel: '画像を生成中',
  imagePreviewTitle: 'ウニ埋めマトリックス画像',
  imagePreviewAlt: 'ウニ埋めマトリックス画像のプレビュー',
  closeImagePreview: '閉じる',
  retryImagePreview: '再試行',
  downloadImage: '保存',
  shareImage: '共有',
  imageChecksLabel: '達成マス数',
  imageGoalLabel: '目標',
  imageGeneratedBy: 'Generated by',
} as const

/** 縦軸・横軸の選択肢1件分の値と表示名 */
export type UniFillMatrixDimensionOption = {
  value: UniFillMatrixDimension
  label: string
}

/** 縦軸・横軸の選択肢 */
export const UNI_FILL_MATRIX_DIMENSION_OPTIONS: UniFillMatrixDimensionOption[] = [
  { value: 'levelConst', label: 'レベル・定数' },
  { value: 'genre', label: 'ジャンル' },
  { value: 'version', label: 'バージョン' },
  { value: 'nameFolder', label: '楽曲名' },
]

/** レベル・定数の軸をレベル別にするか定数別にするかの切り替え選択肢 */
export const UNI_FILL_MATRIX_LEVEL_CONST_AXIS_OPTIONS = [
  { value: 'level', label: 'レベル別' },
  { value: 'chartConstant', label: '定数別' },
] as const satisfies readonly { value: PlayerStatsHeatmapAxis; label: string }[]

/** 初期選択する縦軸 */
export const UNI_FILL_MATRIX_DEFAULT_VERTICAL: UniFillMatrixDimension = 'levelConst'

/** 初期選択する横軸 */
export const UNI_FILL_MATRIX_DEFAULT_HORIZONTAL: UniFillMatrixDimension = 'genre'

/** 保存済みの値がない場合に使う表示設定（縦軸・横軸・レベル別/定数別・%表示） */
export const UNI_FILL_MATRIX_DEFAULT_VIEW_SETTINGS: UniFillMatrixViewSettings = {
  vertical: UNI_FILL_MATRIX_DEFAULT_VERTICAL,
  horizontal: UNI_FILL_MATRIX_DEFAULT_HORIZONTAL,
  levelConstAxis: 'level',
  showPercent: false,
}

/** ウニ埋めマトリックスの表示設定を保存する localStorage キー */
export const UNI_FILL_MATRIX_VIEW_SETTINGS_STORAGE_KEY =
  'chunisupport-uni-fill-matrix-view-settings'

/** 左端の見出し列の名前に使う、レベル・譜面定数の軸の名前 */
const UNI_FILL_MATRIX_LEVEL_CONST_NAMES: Record<PlayerStatsHeatmapAxis, string> = {
  level: 'レベル',
  chartConstant: '譜面定数',
}

/** 表の読み上げ用説明で使う、レベル・譜面定数の軸の名前 */
const UNI_FILL_MATRIX_LEVEL_CONST_CAPTION_NAMES: Record<PlayerStatsHeatmapAxis, string> = {
  level: '譜面定数から換算したレベル',
  chartConstant: '譜面定数',
}

/** 表の読み上げ用説明と左端の見出し列の名前に使う、ジャンルなどの軸の名前 */
const UNI_FILL_MATRIX_SONG_DIMENSION_NAMES: Record<
  Exclude<UniFillMatrixDimension, 'levelConst'>,
  string
> = {
  genre: 'ジャンル',
  version: '追加バージョン',
  nameFolder: '楽曲名',
}

/**
 * 軸の属性の名前を取得する。
 *
 * @param dimension - 縦軸または横軸の属性。
 * @param levelConstAxis - レベル別または譜面定数別。
 * @returns 左端の見出し列の名前に使う軸の名前。
 */
export const getUniFillMatrixDimensionName = (
  dimension: UniFillMatrixDimension,
  levelConstAxis: PlayerStatsHeatmapAxis
): string =>
  dimension === 'levelConst'
    ? UNI_FILL_MATRIX_LEVEL_CONST_NAMES[levelConstAxis]
    : UNI_FILL_MATRIX_SONG_DIMENSION_NAMES[dimension]

/**
 * 表示中の縦軸・横軸を表す表の読み上げ用説明を作る。
 *
 * @param vertical - 縦軸の属性。
 * @param horizontal - 横軸の属性。
 * @param levelConstAxis - レベル別または譜面定数別。
 * @returns 縦軸と横軸の名前を含む説明。
 */
export const formatUniFillMatrixCaption = (
  vertical: UniFillMatrixDimension,
  horizontal: UniFillMatrixDimension,
  levelConstAxis: PlayerStatsHeatmapAxis
): string => {
  const [verticalName, horizontalName] = [vertical, horizontal].map((dimension) =>
    dimension === 'levelConst'
      ? UNI_FILL_MATRIX_LEVEL_CONST_CAPTION_NAMES[levelConstAxis]
      : UNI_FILL_MATRIX_SONG_DIMENSION_NAMES[dimension]
  )
  return `縦軸が${verticalName}、横軸が${horizontalName}の達成状況`
}

/** 名前順フォルダの内部キーから見出しへの対応 */
export const UNI_FILL_MATRIX_NAME_FOLDER_LABELS: ReadonlyMap<string, string> = new Map(
  Object.entries(NAME_FOLDER_LABELS)
)

/** 通常レコード画面へ遷移するときの並び順クエリ（スコア降順） */
export const UNI_FILL_MATRIX_RECORD_SORT_QUERY = 'sortcol=score&sortorder=desc'

/** 難易度選択肢1件分の値と表示名 */
export type UniFillMatrixDifficultyOption = {
  value: UniFillMatrixDifficulty
  label: string
}

/** 初期選択する難易度 */
export const UNI_FILL_MATRIX_DEFAULT_DIFFICULTY: UniFillMatrixDifficultyOption = {
  value: MASTER_ULTIMA_FILTER,
  label: 'MASTER+ULTIMA',
}

/** 難易度の選択肢 */
export const UNI_FILL_MATRIX_DIFFICULTY_OPTIONS: UniFillMatrixDifficultyOption[] = [
  { value: 'ALL', label: '全難易度' },
  { value: 'BASIC', label: 'BASIC' },
  { value: 'ADVANCED', label: 'ADVANCED' },
  { value: 'EXPERT', label: 'EXPERT' },
  { value: 'MASTER', label: 'MASTER' },
  { value: 'ULTIMA', label: 'ULTIMA' },
  UNI_FILL_MATRIX_DEFAULT_DIFFICULTY,
  { value: THEORETICAL_OVER_POWER_TARGET_FILTER, label: 'OP理論値対象' },
]

/** 埋め条件選択肢1件分の値と表示名 */
export type UniFillMatrixAchievementOption = {
  value: PlayerStatsAchievement
  label: string
}

/** 埋め条件の選択肢（表示順） */
export const UNI_FILL_MATRIX_ACHIEVEMENT_OPTIONS: UniFillMatrixAchievementOption[] = (
  [
    'played',
    's',
    'sPlus',
    'ss',
    'ssPlus',
    'sss',
    'sssPlus',
    'fc',
    'aj',
    'ajc',
    'clear',
    'hard',
    'brave',
    'absolute',
    'catastrophe',
  ] as const
).map((value) => ({ value, label: PLAYER_STATS_ACHIEVEMENT_LABEL[value] }))

/** 初期選択する埋め条件（SSS） */
export const UNI_FILL_MATRIX_DEFAULT_ACHIEVEMENT: UniFillMatrixAchievementOption = {
  value: 'sss',
  label: PLAYER_STATS_ACHIEVEMENT_LABEL.sss,
}

/** データ・合計列の幅を1としたときの左端の見出し列の幅。見出しの種類ごとに決める。 */
export const UNI_FILL_MATRIX_LINE_HEADER_WEIGHT: Record<UniFillMatrixHeader['kind'], number> = {
  axis: 0.75,
  group: 1,
}

/** 共通ヒートマップセルの最小幅（min-w-16）に合わせる余白単位数。 */
export const UNI_FILL_MATRIX_DATA_COLUMN_MIN_SPACING = 16

/** 画像内の左右余白（p-6相当）。 */
export const UNI_FILL_MATRIX_IMAGE_PADDING = 24

/** 長い譜面定数表でCanvasのメモリ使用量を抑える出力ピクセル比。 */
export const UNI_FILL_MATRIX_IMAGE_PIXEL_RATIO = 1
