import {
  MASTER_ULTIMA_FILTER,
  THEORETICAL_OVER_POWER_TARGET_FILTER,
} from '../../../constants/chart'
import { PLAYER_STATS_ACHIEVEMENT_LABEL } from '../../../constants/playerStats'
import type { PlayerStatsAchievement } from '../../../utils/playerStatsDashboard'
import type { UniFillMatrixDifficulty } from '../../../utils/uniFillMatrix'

/** ウニ埋めマトリックス画面の表示文言。タイトルと説明文はツール一覧の定義を参照すること。 */
export const UNI_FILL_MATRIX_COPY = {
  difficultyLabel: '難易度',
  achievementLabel: '埋め条件',
  axisLabel: '縦軸',
  percentToggle: '%表示',
  levelHeader: 'レベル',
  chartConstantHeader: '譜面定数',
  totalHeader: '合計',
  levelCaption: '縦軸が譜面定数から換算したレベル、横軸がジャンルの達成状況',
  chartConstantCaption: '縦軸が譜面定数、横軸がジャンルの達成状況',
  cellActionLabel: '未達成の譜面をレコードで表示',
  recordNavigationError: 'レコード画面へ移動できませんでした。',
  imageSaveLabel: '画像化・共有',
  imageSaveError: '画像を生成できませんでした。',
  imageShareError: '画像を共有できませんでした。',
  imageCapturingLabel: '画像を生成中',
  imagePreviewTitle: 'ウニ埋めマトリックス画像',
  imagePreviewAlt: 'ウニ埋めマトリックス画像のプレビュー',
  closeImagePreview: '閉じる',
  retryImagePreview: '再試行',
  downloadImage: '保存',
  shareImage: '共有',
  imageChecksLabel: '達成マス数',
  imageGoalLabel: '目標',
  imageGeneratedBy: 'Generated by',
} as const

/** 通常レコード画面へ遷移するときの並び順クエリ（スコア降順） */
export const UNI_FILL_MATRIX_RECORD_SORT_QUERY = 'sortcol=score&sortorder=desc'

/** 難易度選択肢1件分の値と表示名 */
export type UniFillMatrixDifficultyOption = {
  value: UniFillMatrixDifficulty
  label: string
}

/** 初期選択する難易度 */
export const UNI_FILL_MATRIX_DEFAULT_DIFFICULTY: UniFillMatrixDifficultyOption = {
  value: MASTER_ULTIMA_FILTER,
  label: 'MASTER+ULTIMA',
}

/** 難易度の選択肢 */
export const UNI_FILL_MATRIX_DIFFICULTY_OPTIONS: UniFillMatrixDifficultyOption[] = [
  { value: 'ALL', label: '全難易度' },
  { value: 'BASIC', label: 'BASIC' },
  { value: 'ADVANCED', label: 'ADVANCED' },
  { value: 'EXPERT', label: 'EXPERT' },
  { value: 'MASTER', label: 'MASTER' },
  { value: 'ULTIMA', label: 'ULTIMA' },
  UNI_FILL_MATRIX_DEFAULT_DIFFICULTY,
  { value: THEORETICAL_OVER_POWER_TARGET_FILTER, label: 'OP理論値対象' },
]

/** 埋め条件選択肢1件分の値と表示名 */
export type UniFillMatrixAchievementOption = {
  value: PlayerStatsAchievement
  label: string
}

/** 埋め条件の選択肢（表示順） */
export const UNI_FILL_MATRIX_ACHIEVEMENT_OPTIONS: UniFillMatrixAchievementOption[] = (
  [
    'played',
    's',
    'sPlus',
    'ss',
    'ssPlus',
    'sss',
    'sssPlus',
    'fc',
    'aj',
    'ajc',
    'clear',
    'hard',
    'brave',
    'absolute',
    'catastrophe',
  ] as const
).map((value) => ({ value, label: PLAYER_STATS_ACHIEVEMENT_LABEL[value] }))

/** 初期選択する埋め条件（SSS） */
export const UNI_FILL_MATRIX_DEFAULT_ACHIEVEMENT: UniFillMatrixAchievementOption = {
  value: 'sss',
  label: PLAYER_STATS_ACHIEVEMENT_LABEL.sss,
}

/** ジャンル・合計列の幅を1としたときの縦軸列の幅。 */
export const UNI_FILL_MATRIX_AXIS_COLUMN_WEIGHT = 0.5

/** 共通ヒートマップセルの最小幅（min-w-16）に合わせる余白単位数。 */
export const UNI_FILL_MATRIX_DATA_COLUMN_MIN_SPACING = 16

/** 画像内の左右余白（p-6相当）。 */
export const UNI_FILL_MATRIX_IMAGE_PADDING = 24

/** 長い譜面定数表でCanvasのメモリ使用量を抑える出力ピクセル比。 */
export const UNI_FILL_MATRIX_IMAGE_PIXEL_RATIO = 1
