export { default as AdminCoursesPage } from './AdminCoursesPage'
export { default as AdminHonorsPage } from './AdminHonorsPage'
export { default as AdminPage } from './AdminPage'
export { default as AdminRatingImageDomPreviewPage } from './AdminRatingImageDomPreviewPage'
export { default as AdminSongsPage } from './AdminSongsPage'
export { default as AdminUsersPage } from './AdminUsersPage'
export { default as AdminVersionsPage } from './AdminVersionsPage'
