name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check third-party licenses
        run: pnpm run licenses:check

      - name: Check
        run: pnpm run check:ci

      - name: Build
        run: pnpm run build
