name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_BACKEND_URL: ${{ vars.PUBLIC_BACKEND_URL }}
      PUBLIC_FRONTEND_URL: ci-frontend
      PUBLIC_DOCUMENTATION_URL: ci-documentation
      PUBLIC_BOOKMARKLET_URL: ci-bookmarklet
      PUBLIC_BOOKMARKLET_ENTRYPOINT: ci-bookmarklet-entrypoint
      PUBLIC_FB_API_KEY: ${{ vars.PUBLIC_FB_API_KEY }}
      PUBLIC_FB_AUTH_DOMAIN: ${{ vars.PUBLIC_FB_AUTH_DOMAIN }}
      PUBLIC_FB_PROJECT_ID: ${{ vars.PUBLIC_FB_PROJECT_ID }}
      PUBLIC_FB_STORAGE_BUCKET: ${{ vars.PUBLIC_FB_STORAGE_BUCKET }}
      PUBLIC_FB_MESSAGING_SENDER_ID: ${{ vars.PUBLIC_FB_MESSAGING_SENDER_ID }}
      PUBLIC_FB_APP_ID: ${{ vars.PUBLIC_FB_APP_ID }}
      PUBLIC_FB_MEASUREMENT_ID: ${{ vars.PUBLIC_FB_MEASUREMENT_ID }}
      PUBLIC_CF_TURNSTILE_SITE_KEY: ${{ vars.PUBLIC_CF_TURNSTILE_SITE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check third-party licenses
        run: pnpm run licenses:check

      - name: Check
        run: pnpm run check:ci

      - name: Build
        run: pnpm run build
